### ISSUE TITLE
hillshadeレイヤーのmaxzoomを設定できる？

### ISSUE THREAD

**Issue by keichan34** [geoloniamaps/basic#103]
現状、z16-z18でもgsi-demのタイルがリクエストされていますが、hillshadeが見えなくなったズームまでmaxzoom設定できるかな？

https://github.com/geoloniamaps/basic/blob/e0cde00d6783875c3bf98a17e1b5c8274ebead24/layers/hillshading.yml#L1-L11

**Comment by naogify** [comment]
@keichan34 
maxzoom: 12 を設定した方が良いですね! スタイル側で指定しようと思います
