### ISSUE TITLE
駅とバスの見分けがつきにくい

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geoloniamaps/basic#112]
交通系ということで、同じ色になっており、しかも似てる。

**Comment by u5t** [comment]
@ShinichiNishikawa 
こちら検討してみました。

## 現状
https://geoloniamaps.github.io/basic/#16.86/35.675796/139.762154
![現状](https://user-images.githubusercontent.com/3376589/157391462-a53fc89e-f165-40d7-ba4a-db73c3d34ed1.png)

■駅名がついているアイコンが多く、わかりにくい状況。
![駅名付transport](https://user-images.githubusercontent.com/3376589/157391512-56597129-78b8-4eed-843d-6f2493634b30.png)

バスと駅だけではなく、その他要素も含めて全体的にバランスを見直しました。

## 調整案
![調整](https://user-images.githubusercontent.com/3376589/157391691-08c9060c-fcc6-4546-bfc7-e3b267f3bc52.png)

パット見たときに駅名がまず目に入るように調整しました。

・バス→シンプルなアイコンに変更。
・地下鉄出口→目立つ必要のない要素なのでシンプルなアイコンに変更。
駅名表示だと紛らわしく、番号のほうがわかりやすいので変更。
・JR→JRカラーのアイコンに変更。文字もアイコンも少し大きく。」
・地下鉄→少し大きくしても良いかも。

修正にあたって複数のタスクになりそうなので、今後の作業はissueを分割して別々に対応していこうと思っています。

**Comment by u5t** [comment]
地下鉄が実線で乗っていたほうが、さらに駅だとわかりやすいかもしれないので、こちらは別issueで対応予定です。
![地下鉄実線](https://user-images.githubusercontent.com/3376589/157393000-64433915-5bfa-42aa-9b97-0bf114c7d861.png)

https://github.com/geoloniamaps/basic/issues/89

**Comment by ShinichiNishikawa** [comment]
めちゃ良くなってる！

**Comment by u5t** [comment]
こちらデザインの方向性が決まったので、今後の作業を別issueに分割しました。
こちらのissueはcloseいたします
