### ISSUE TITLE
県境の色を調整

### ISSUE THREAD

**Issue by naogify** [geoloniamaps/basic#119]

**Comment by u5t** [comment]
@naogify 県境の色調整してみました。

■赤色が少し強すぎたので馴染むようにしたver
![FireShot Capture 186 - Deploy Preview - Geolonia Map - u5t github io](https://user-images.githubusercontent.com/3376589/154884941-1568b3f6-d664-4270-a15d-c349f68d3b25.png)
https://github.com/u5t/experiment-zoom/pull/2

■色を目立たないグレーにして、代わりに太さを太くしたver
![FireShot Capture 187 - Deploy Preview - Geolonia Map - u5t github io](https://user-images.githubusercontent.com/3376589/154884926-1ef31431-7313-4a0a-bb8d-2aa4940e444e.png)
https://github.com/u5t/experiment-zoom/pull/1

赤のほうが目立ちますが、他にアイコンや地名が出てきたときに色がガチャついてしまう可能性はあるかも？

**Comment by naogify** [comment]
@u5t 
ありがとうございます! 赤色はかなり目立つので、県境をどれぐらい目立たせるのかも含めて検討が必要ですね。
一旦、`■色を目立たないグレーにして、代わりに太さを太くしたver` で良いかと思います!
