### ISSUE TITLE
白丸アイコンを追加

### ISSUE THREAD

**Issue by naogify** [geoloniamaps/basic#120]

**Comment by u5t** [comment]
@naogify 
basic-colorアイコンのcircle-strokedの
丸の中が白塗りになっているsvgデータを作成しました。

下記がサンプルです
### before
![circle-stroked-before](https://user-images.githubusercontent.com/3376589/155926815-90c69528-8bd6-4cf8-9450-494e95dc77c9.png)


### after
![circle-stroked-after](https://user-images.githubusercontent.com/3376589/155926827-12df345d-4c4d-478e-91ff-273d5ce6abbb.png)


問題なければspritesの方にプルリク送ろうと思うんですが、
こちらは
・circle-stroked-11.svg
・circle-stroked-15.svg
を上書きしたほうが良いでしょうか？
それとも別ファイル名でアップしたほうが良いでしょうか？

**Comment by naogify** [comment]
@u5t ありがとうございます！上書きでPRお願いしたいです。(近いデザインのアイコンが複数あるとユーザーの選択の手間が増えると思ったので)

**Comment by naogify** [comment]
Closed by https://github.com/geolonia/sprites.geolonia.com/pull/43
