### ISSUE TITLE
謎の線が出ている

### ISSUE THREAD

**Issue by naogify** [geoloniamaps/basic#129]
https://maps.geolonia.com/#style=geolonia/basic&map=11/39.5991/141.1501

![スクリーンショット 2022-02-25 10 30 16](https://user-images.githubusercontent.com/8760841/155636894-59fd3741-6182-4d09-bf44-d17eed646034.png)

**Comment by keichan34** [comment]
あ、landcover=wood のせんですよね。。これは OSMのデータの形がちょっとおかしいためにこうなってるんですね。タイルで修正しようと思っています
ちなみに、この問題は日本で一番目立つのが岩手県と高知県です
https://maps.geolonia.com/#style=geolonia/basic&map=11/33.0566/132.8948&lang=ja
他の都道府県もある程度出てるときはあるけど今の所その2県で一番困っている。。

**Comment by keichan34** [comment]
ちなみに、解決としてはちょっと進んでいて、OSMからのデータを抽出してから結合して、shapefileに入れたらそれをtilemakerに入れる、というプロセスになります

**Comment by naogify** [comment]
@keichan34 
ありがとうございます! ではこの issue は閉じます。（一応、tilemaker の方に issue 立てておきます!）
