### ISSUE TITLE
Attribution がおかしい

### ISSUE THREAD

**Issue by miya0001** [geoloniamaps/basic#14]
![](https://www.evernote.com/l/ABVKvcAohD1M0bQl7EkVkd2jGETdLcXXbdYB/image.png)

tile.json に適切な attribution がセットされていない？

**Comment by keichan34** [comment]
OpenStreetMap の一つに `/` が入って、もう一つ入ってないのでうまく統合されていないっぽいですね。 Attribution を全部整理する必要ありそうですね。
