### ISSUE TITLE
キャッシュが無いときに地図の表示が重い

### ISSUE THREAD

**Issue by miya0001** [geoloniamaps/basic#15]
* ズームレベル０のときの表示時間が５秒から１０秒ぐらい？
* 高ズームでもレンダリングがひどく遅いときが多い。
* なぜか同じタイルが３回ロードされている。

![](https://www.evernote.com/l/ABWYuzwJMNhNhaAKhUpC0H4MPBBAbboIA0cB/image.png)

**Comment by keichan34** [comment]
@miya0001 @takamotobiz なるほど。。。今確認したところ、最初のロードには同じタイルを3回読み込んでるんですが、ズームしたり場所移動したりすると各タイルは1回しか読み込まないんですね。

**Comment by keichan34** [comment]
複数回読み込まれてるのは色々調査しましたが、再現出来たのはズームアウトされていたとき(z0, z1) で、同じタイルが同じ画面で違う場所で表示されていたときでした。(例えば、 0/0/0 がラップアラウンドされて並べて２回表示されたとき＝そのタイルリクエストが２個あった)
これはmapbox-gl/maplibre-gl両方同じ挙動で、おそらく修正出来ないんじゃないかなと思います笑
ただ、ズームインされているときは再現できず。
とりあえず、 oceanus を tileserver で配信するようにしてちょっと早くなったような気がする。タイル自体の改善も進めています。

**Comment by keichan34** [comment]
oceanus の軽量化反映済み
