### ISSUE TITLE
四国の一部の川のポリゴンがない

### ISSUE THREAD

**Issue by naogify** [geoloniamaps/basic#21]
吉野川など一部の川でポリゴンがない。

国内に川と湖を追加するスタイルレイヤー `water-lake-ja` は source layer `water` の`class: lake` をフィルターして表示しているので、四国の川のポリゴンは別の class が付与されている可能性がありそう。

https://geolonia.github.io/preview/#14.2/34.09038/134.57552

<img width="868" alt="スクリーンショット 2021-06-18 10 46 36" src="https://user-images.githubusercontent.com/8760841/122493348-7e380c80-d022-11eb-8409-c3958f5b1bf2.png">

**Comment by keichan34** [comment]
tilemakerの方にはありますね。。。
https://deploy-preview-20--style-basic.netlify.app/#14.2/34.09199/134.56838

**Comment by naogify** [comment]
tilemakerの方を確認してみると吉野川はあったのですが、今切川の水ポリゴンが無いことに気づきました。。。

https://deploy-preview-20--style-basic.netlify.app/#14.52/34.12058/134.59214

![スクリーンショット 2021-06-23 11 16 03](https://user-images.githubusercontent.com/8760841/123024878-bf5e6100-d414-11eb-831e-45b0f0ea7d66.png)

**Comment by keichan34** [comment]
ここにも見つかって、
https://deploy-preview-20--style-basic.netlify.app/#16.1/33.554848/133.530916

OSMと確認しようとしたら、
<img width="1055" alt="Screen Shot 2021-06-23 at 11 48 14" src="https://user-images.githubusercontent.com/1064513/123027515-e7e85a00-d418-11eb-9adc-7078ef84cb51.png">

tag が outdated というよというように言われてる。。おそらくこれかな。
tilemakerの設定を古いタグ方式でも読み込めるように設定します！
