### ISSUE TITLE
お堀の名前のラベル、陸地の地物のものより大きく表示される

### ISSUE THREAD

**Issue by kamataryo** [geoloniamaps/basic#22]
お堀の名前よりも、陸地の地物の方がユーザーの関心は大きそう。
ある程度大きい自然湖沼はラベルが大きく表示されたほうがいいが、皇居のお堀などは名前を非表示にした方がいい？
https://deploy-preview-20--style-basic.netlify.app/#14.1/35.68191/139.75244

**Comment by keichan34** [comment]
確かに。`water_name` レイヤーに入ってる。 OSM `water=moat` の場合、アトリビュートを付けてそれで優先度を制御したほうが良いのか、`water_name` 全体の優先度を低くしたほうが良いのか、どう思います。。？

**Comment by kamataryo** [comment]
@keichan34 水域のポリゴンが混み合っているときに、たくさんラベルが表示されているとおかしく感じる様に思いました。それで、この様なケースはお堀くらいしかないと思うので、 `water=moat` がフィルターできるのであればそちらを制御したほうがいいかと思います。

自然湖沼で名前がついているポリゴンが混み合っていそうな場所があまり思いつかないですが、例えば以下の知床五湖などの表示は自然でアリかと。
https://deploy-preview-20--style-basic.netlify.app/#14.3/44.12613/145.08029

**Comment by kamataryo** [comment]
お堀は、やっぱり水域の名前が出ていて変になっていることが多いですね。

鶴ヶ城: https://deploy-preview-20--style-basic.netlify.app/#15.76/37.485967/139.92972
彦根城: https://deploy-preview-20--style-basic.netlify.app/#14.75/35.27596/136.2518

**Comment by keichan34** [comment]
鶴ヶ城 の五軒丁堀おかしいですね、ポリゴンが無い。。？
<img width="273" alt="Screen Shot 2021-06-23 at 11 13 36" src="https://user-images.githubusercontent.com/1064513/123024475-10ba2080-d414-11eb-8ea1-98dfbfb3ac66.png">

**Comment by keichan34** [comment]
というか完全に欠損してるね
<img width="1382" alt="Screen Shot 2021-06-23 at 11 14 51" src="https://user-images.githubusercontent.com/1064513/123024581-3d6e3800-d414-11eb-913e-78c7e885b51a.png">

**Comment by kamataryo** [comment]
日比谷公園もないですね..
https://deploy-preview-20--style-basic.netlify.app/#14.91/35.67255/139.75649
<img width="465" alt="スクリーンショット 2021-06-23 11 15 08" src="https://user-images.githubusercontent.com/6292312/123024632-4f4fdb00-d414-11eb-8200-e5a03f8042af.png">

**Comment by kamataryo** [comment]
鶴ヶ城は地元なんですけど、ここは一部水があるので空堀というわけではないです。

**Comment by keichan34** [comment]
ありがとうございました！OSM確認したらちゃんとwaterとして入ってるのでtilemakerの設定かな？確認します。

**Comment by keichan34** [comment]
@kamataryo waterが表示されていない問題を修正するものを 88c5322 にプッシュしました、もう一度確認いただけますか？
お堀の名前はtileを修正しないと行けなさそうなのでこれから修正します :bow:

**Comment by keichan34** [comment]
minzoom=15 に設定して `subclass=moat` を設定してみます。スタイル修正は後ほどタイル生成終わった後 :bow:

https://github.com/geolonia/tilemaker-geolonia/commit/252035172e40f3b54ee9b4bdd5a104ff63521fc4

**Comment by kamataryo** [comment]
@keichan34 表示されていなかった水域、良さそうですね。確認していなかった場所でもあるべき水域が色々増えている気がします。ありがとうございます！

**Comment by keichan34** [comment]
確認ありがとうございました。原因としては、landcover のレイヤーがwaterより先に来ていたので公園などあったときにwater ポリゴンが隠れていたんですね。。 :bow:
