### ISSUE TITLE
男木島周辺の航路が正しいかどうか確認する

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geoloniamaps/basic#25]
https://deploy-preview-20--style-basic.netlify.app/#11.28/34.4311/134.0602

![スクリーンショット 2021-06-23 12 59 15](https://user-images.githubusercontent.com/1124652/123033543-e02db300-d422-11eb-9bf4-3632516402ce.png)

高松から男木島と女木島の間を抜けて、豊島に向かう航路が書かれているが、これはなんだろう。

**Comment by keichan34** [comment]
メモ https://www.openstreetmap.org/way/369518835#map=13/34.4221/134.0487

**Comment by ShinichiNishikawa** [comment]
臨時便がある
https://www.t-ferry.com/schedule/

**Comment by ShinichiNishikawa** [comment]
普段からあるそうでした。

**Comment by keichan34** [comment]
@ShinichiNishikawa 一旦クローズしますね。もし編集や調整したい場合は、OSMのデータや最新データを参照しながらOSMを更新しましょう
