### ISSUE TITLE
島の名前を表示したい

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geoloniamaps/basic#26]
### 大きいズーム
![スクリーンショット 2021-06-23 13 32 45](https://user-images.githubusercontent.com/1124652/123036210-a4491c80-d427-11eb-9f96-a5282a940634.png)

https://deploy-preview-20--style-basic.netlify.app/#10.4/34.4155/134.0306

### ひいて見たところ

![スクリーンショット 2021-06-23 13 34 14](https://user-images.githubusercontent.com/1124652/123036280-c2af1800-d427-11eb-8996-44ca2230d4bf.png)

https://deploy-preview-20--style-basic.netlify.app/#13.27/34.4048/134.04604

**Comment by keichan34** [comment]
ほしいですねー。

メモ https://www.openstreetmap.org/relation/2950943
