### ISSUE TITLE
水域の色味の見直し

### ISSUE THREAD

**Issue by kamataryo** [geoloniamaps/basic#30]
200m以浅と200m以深で色がマッチしていないように感じる。200m以浅は赤みが強い。

|depth|hex|rgb|hsl|source|layer|
|---:|:---|:---|:---|:---|:---|
|    0m|`#a0c8f0`|`rgb(160, 200, 240)`|`hsl(210.0, 72.7%, 78.4%)`|`geolonia-water`|海・川|
|  200m|`#02b7ed`|`rgb(002, 183, 237)`|`hsl(193.8, 98.3%, 46.9%)`|`oceanus`|海|
| 1000m|`#02aae4`|`rgb(002, 170, 228)`|`hsl(195.4, 98.3%, 45.1%)`|`oceanus`|海|
| 2000m|`#0393d4`|`rgb(003, 147, 212)`|`hsl(198.7, 97.2%, 42.2%)`|`oceanus`|海|
| 3000m|`#0388cd`|`rgb(003, 136, 205)`|`hsl(200.5, 97.1%, 40.8%)`|`oceanus`|海|
| 4000m|`#0479c3`|`rgb(004, 121, 195)`|`hsl(203.2, 96.0%, 39.0%)`|`oceanus`|海|
| 5000m|`#0563b5`|`rgb(005, 099, 181)`|`hsl(208.0, 94.6%, 36.5%)`|`oceanus`|海|
| 6000m|`#0645a1`|`rgb(006, 069, 161)`|`hsl(215.6, 92.8%, 32.7%)`|`oceanus`|海|
| 7000m|`#072d91`|`rgb(007, 045, 145)`|`hsl(223.5, 90.8%, 29.8%)`|`oceanus`|海|
| 8000m|`#081a84`|`rgb(008, 026, 132)`|`hsl(231.3, 88.6%, 27.5%)`|`oceanus`|海|
| 9000m|`#090979`|`rgb(009, 009, 121)`|`hsl(240.0, 86.2%, 25.5%)`|`oceanus`|海|
|10000m|`#111188`|`rgb(017, 017, 136)`|`hsl(240.0, 77.8%, 30.0%)`|`oceanus`|海|

**Comment by kamataryo** [comment]
プラン1:
`geolonia-water` を修正して赤みを減らす。

|depth|old hex|new hex|modified|
|---:|:---|:---|:---|
|    0m|`#a0c8f0`|`#02b9f0`|true|
|  200m|`#02b7ed`|`#02b7ed`|
| 1000m|`#02aae4`|`#02aae4`|
| 2000m|`#0393d4`|`#0393d4`|
| 3000m|`#0388cd`|`#0388cd`|
| 4000m|`#0479c3`|`#0479c3`|
| 5000m|`#0563b5`|`#0563b5`|
| 6000m|`#0645a1`|`#0645a1`|
| 7000m|`#072d91`|`#072d91`|
| 8000m|`#081a84`|`#081a84`|
| 9000m|`#090979`|`#090979`|
|10000m|`#111188`|`#111188`|

**Comment by kamataryo** [comment]
プラン2:
`oceanus` の200m や 1000m に赤みを追加する。

|depth|old rgb|new rgb|modified|
|---:|:---|:---|:---|
|    0m|`rgb(160, 200, 240)`|`rgb(160, 200, 240)`|
|  200m|`rgb(002, 183, 237)`|`rgb(140, 183, 237)`|true|
| 1000m|`rgb(002, 170, 228)`|`rgb(100, 170, 228)`|true|
| 2000m|`rgb(003, 147, 212)`|`rgb(050, 147, 212)`|true|
| 3000m|`rgb(003, 136, 205)`|`rgb(020, 136, 205)`|true|
| 4000m|`rgb(004, 121, 195)`|`rgb(010, 121, 195)`|true|
| 5000m|`rgb(005, 099, 181)`|`rgb(005, 099, 181)`|
| 6000m|`rgb(006, 069, 161)`|`rgb(006, 069, 161)`|
| 7000m|`rgb(007, 045, 145)`|`rgb(007, 045, 145)`|
| 8000m|`rgb(008, 026, 132)`|`rgb(008, 026, 132)`|
| 9000m|`rgb(009, 009, 121)`|`rgb(009, 009, 121)`|
|10000m|`rgb(017, 017, 136)`|`rgb(017, 017, 136)`|

**Comment by keichan34** [comment]
プラン1の水色がちょっと濃いかな、、どちらかというと僕はプラン2の方が良い気がする。誰に確認してもらうのがいいかな笑

**Comment by kamataryo** [comment]
現在:
<img width="2004" alt="current" src="https://user-images.githubusercontent.com/6292312/124435565-14ed2300-ddb0-11eb-9bc5-44f60be090e2.png">
修正:
<img width="1987" alt="modified" src="https://user-images.githubusercontent.com/6292312/124435576-16b6e680-ddb0-11eb-83e8-3c5f8529633b.png">

**Comment by keichan34** [comment]
@kamataryo ここの「修正」はプラン2ですよね？

**Comment by kamataryo** [comment]
はい、そうです。

**Comment by naogify** [comment]
自分もプラン2の方が馴染んでいる気がします…！

**Comment by naogify** [comment]
こちら新スタイルで、海の色を調整したのでクローズします。また必要があればオープンお願いします。
