### ISSUE TITLE
3D表示用のプロパティがない

### ISSUE THREAD

**Issue by miya0001** [geoloniamaps/basic#31]
https://github.com/geolonia/basic/blob/master/style.json#L4341-L4362

以下２つのプロパティが必要？

* `render_height`
* `render_min_height`

**Comment by keichan34** [comment]
ああ、この情報ってまだ tilemaker のタイルに入っていないんです。追加します！

**Comment by miya0001** [comment]
これよく見たらプロパティ名がなんか変ですよね。osm のタグ名にあわせたほうがいいかも。。。

**Comment by keichan34** [comment]
osm はちょっとややこしくて、 building の階数あったりメートルの高さがあったりするので、おそらく render_height と render_min_height に正規化してると思うんですね、OMTの方で

**Comment by miya0001** [comment]
なるほど！

**Comment by keichan34** [comment]
調べたところ、 OSMの [height=*](https://wiki.openstreetmap.org/wiki/Key:height) と [min_height=*](https://wiki.openstreetmap.org/wiki/Key:min_height) に該当します。

実装の予定：
* height や min_height あればそのまま利用する。
* ない場合は、 [building:levels=*](https://wiki.openstreetmap.org/wiki/Key:building:levels) と [building:min_level=*](https://wiki.openstreetmap.org/wiki/Key:building:min_level) を 3.5mでかける (適当です、[知恵袋だけどこういう回答](https://realestate.yahoo.co.jp/knowledge/chiebukuro/detail/14130149609/)を参考に3.5mにしてみた)

**Comment by keichan34** [comment]
render_height / render_min_height のパラメータが入ったプレビュー
<img width="1067" alt="Screen Shot 2021-07-05 at 15 35 08" src="https://user-images.githubusercontent.com/1064513/124427654-a192e380-dda6-11eb-8feb-ac2cb8815d0e.png">

**Comment by keichan34** [comment]
今日中に3dパラメータが入ったタイルをリリース

**Comment by keichan34** [comment]
3dパラメータ入ったタイルデプロイ済み
