### ISSUE TITLE
線路がなくなってる。。？

### ISSUE THREAD

**Issue by keichan34** [geoloniamaps/basic#35]
あ、地下鉄だけかもしれない

https://geolonia.github.io/preview/?style=geolonia/basic#16.2/35.712192/139.741119/20

**Comment by naogify** [comment]
調べてみると、ここは車両基地なので、なくなっていても問題なさそうです。

Google map でも同じでした。
https://www.google.co.jp/maps/@35.7117513,139.7401311,19.09z?hl=ja

クローズします!
