### ISSUE TITLE
海上国道の扱い

### ISSUE THREAD

**Issue by kamataryo** [geoloniamaps/basic#39]
海上国道など普通ではない国道のラベルは表示しない方が良いかも。
<img width="1440" alt="スクリーンショット 2021-07-25 7 26 54" src="https://user-images.githubusercontent.com/6292312/126882424-38a614b2-bb43-489f-982b-f033ad26caf7.png">

https://geolonia.github.io/preview/?style=geolonia/basic#14.02/34.48637/133.95827

**Comment by kamataryo** [comment]
ついでに変な国道を確認。

## 青森県龍飛の階段国道

これは残しておいていいかな？

<img width="1280" alt="スクリーンショット 2021-07-26 9 05 13" src="https://user-images.githubusercontent.com/6292312/126917851-9d984980-7c51-4afd-ae72-fae6296d280d.png">

https://geolonia.github.io/preview/?style=geolonia/basic#18.18/41.258489/140.344266

**Comment by kamataryo** [comment]
## 青崩峠

表示されてる。未通区間なので消せる方がいいかも。
<img width="1280" alt="スクリーンショット 2021-07-26 9 10 32" src="https://user-images.githubusercontent.com/6292312/126917994-56ff05b9-c5ca-4556-84d5-118a57144e71.png">

https://geolonia.github.io/preview/?style=geolonia/basic#15.41/35.253149/137.91398

**Comment by kamataryo** [comment]
## 清水峠

国道291号の未成区間の清水峠は表示されていない。

<img width="1440" alt="スクリーンショット 2021-07-26 9 14 43" src="https://user-images.githubusercontent.com/6292312/126918118-a5563540-1958-4d2e-b278-c6f8f65e08c3.png">

https://geolonia.github.io/preview/?style=geolonia/basic#12.22/36.91183/138.91877

**Comment by keichan34** [comment]
@kamataryo 
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dproposed
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dplanned

転送みたいですね。。どうしましょう。タイルレベルで削除したほうが良いような気がしますね。。どう思います？

**Comment by kamataryo** [comment]
@keichan34 
> （Tag:highway=plannedから転送）

なるほど。 planned が現地コミュニティで慣習的に使われてるって感じですかね。タイルレベルで削除する方が良さそうに思えてきましたが、明確にはどのような基準で対応すべきでしょう？
こういった表記の揺れのようなものはタイル生成過程で吸収すべき、という感じ？

**Comment by keichan34** [comment]
日本の場合は海上国道はhighway=plannedとしてマッピングしてるんですね、色々確認すると。明確にこのルールがどこかに書いてるかちょっとまだ探せてないんですが。。

https://wiki.openstreetmap.org/wiki/Japan_tagging#Road_Types
