### ISSUE TITLE
Attribution から Geolonia が消えてる

### ISSUE THREAD

**Issue by miya0001** [geoloniamaps/basic#46]
OSM 以外にも依存しているものがあるので、それらを明記するためにあったほうが良いと思われる。

元のリンク先は以下。
https://geolonia.com/credit/

内容については見直しが必要かもですね。

**Comment by keichan34** [comment]
attributionがtiles.jsonから抜けてるっぽいですね。。タイル生成で確認します。

https://tileserver.geolonia.com/v2/metadata.json
https://tileserver.geolonia.com/oceanus/metadata.json

oceanus も確認します

**Comment by keichan34** [comment]
oceanus は別issueで管理
まずはbasicの © Geolonia を戻しました :bow:

**Comment by takamotobiz** [comment]
既にクローズしたと思いますが、以下、使用データにつき回答します。
結論は、`© Geolonia | © OpenStreetMap` 以外のアトリビューションは不要です。

Oceanusで使っているデータは以下の通りです。
1. japanarea.shp     ：日本の範囲を示すシェープファイル
2. japan-bl.shp      ：国境線シェープファイル
3. japannt_forest.shp：日本の森林のシェープファイル
4. japan-nt-name.shp ：北方領土地名シェープファイル
5. naturalearth      ：NaturalEarth（getne.shにて作成）
6. pref-capital      ：県庁所在地補完用CSVファイル

1〜4はQGISで自作、5はパブリックドメインです。
6は作成元の[アマノ技研さん](https://amano-tec.com/data/index.html)（私と同じ個人の技術士事務所のようです）に問い合わせたところ、”ご自由にお使いください。”とのことでしたので、クレジットなしで問題ありません。参考までに、データのみの再配布はNGとのことです。

**Comment by keichan34** [comment]
@takamotobiz ありがとうございました！よくわかりました。
