### ISSUE TITLE
河川名が道路？レイヤーの下に表示されている。

### ISSUE THREAD

**Issue by naogify** [geoloniamaps/basic#54]
https://geolonia.github.io/preview/?style=geolonia%2Fbasic#13.79/35.10434/136.72662
![スクリーンショット 2021-09-10 16 13 58](https://user-images.githubusercontent.com/8760841/132814858-f5616aae-af33-4a01-8356-a00b1d47559a.png)

**Comment by kamataryo** [comment]
これも同じかな。
https://maps.geolonia.com/#style=geolonia/basic&lang=ja&map=14/35.35781/136.29012

**Comment by kamataryo** [comment]
`highway-trunk` vs `waterway-name`

**Comment by kamataryo** [comment]
修正が確認できました。
