### ISSUE TITLE
Geolonia のタイルを使うと maputnik の inspect モードが動かない

### ISSUE THREAD

**Issue by kamataryo** [geoloniamaps/basic#60]
調査して直したい。

**Comment by kamataryo** [comment]
Maputnik で表示されるのは、tiles.json の `vector_layers` が定義されているときだけかもしれない。
Geolonia のタイルでも特定のレイヤーを選択するとそのレイヤーのみがインスペクトされる。

<img width="1440" alt="スクリーンショット 2021-11-01 10 19 34" src="https://user-images.githubusercontent.com/6292312/139608870-dbedf818-203d-4fb2-9ad7-d7cb027127eb.png">

**Comment by keichan34** [comment]
なるほど。tilemakerにこれを追加してみましょうか？

**Comment by kamataryo** [comment]
そうですね。公式のタイルでは `vector_layers` プロパティを提供できていると良さそうです。
全てのタイルで出現するレイヤーの数は限定できないから tiles.json のサイズが大きくなる可能性があるけれど、実用上は問題ないかな。

**Comment by kamataryo** [comment]
NOTE:
やはり vector_layers プロパティがあると動作することがわかった。
Geolonia の開発環境のタイルで確認。

<img width="1440" alt="スクリーンショット 2021-11-12 16 36 10" src="https://user-images.githubusercontent.com/6292312/141429709-e5365ff0-472a-485f-af56-10207b04c46d.png">
