### ISSUE TITLE
歩道のスタイルを検討

### ISSUE THREAD

**Issue by naogify** [geoloniamaps/basic#87]
歩道が分かりにくいので、他社のマップを参考にしながら

![スクリーンショット 2021-11-22 18 09 22](https://user-images.githubusercontent.com/8760841/142833698-c2653e41-9d87-495b-bc08-8be7108b8a3a.png)

https://maps.geolonia.com/#style=geolonia/basic&lang=ja&map=20/35.6824715/139.7736711

**Comment by marcofabrika** [comment]
ZL15から半透明（0.5）で細めに表示、17で全表示に変更しています。
