### ISSUE TITLE
地下鉄が必要か検討

### ISSUE THREAD

**Issue by naogify** [geoloniamaps/basic#89]
Related to #86 

![スクリーンショット 2021-11-22 17 41 11](https://user-images.githubusercontent.com/8760841/142829589-49d38b24-6d0c-4b52-a1a1-d0d5560d36ab.png)

https://maps.geolonia.com/#style=geolonia/basic&lang=ja&map=20/35.6824715/139.7736711

**Comment by ShinichiNishikawa** [comment]
現状では、線路の経路自体の表示はいったんいらないような気がします。

**Comment by naogify** [comment]
自分も、そう思います。

線路が途中から地下に入る場合（例：阪急電車）は、急に線路が消えた様に見えるので、線路の終わりを丸くするなどして、トンネルに入ったと伝えたいですね。


https://maps.geolonia.com/#style=geolonia/basic&lang=ja&map=19/34.713155/135.51153
<img width="1274" alt="スクリーンショット 2021-11-25 15.36.46.png (342.3 kB)" src="https://img.esa.io/uploads/production/attachments/17590/2021/11/25/102238/f50a1dc8-58bf-4acf-9d93-d7a43471750f.png">

**Comment by naogify** [comment]
地下鉄は実線で書いた方がわかりやすい。（ @u5t さんに実線で試してもらう）
